/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Loguin` | `/Loguin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Register` | `/Register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Chat` | `/Chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/NewSpotScreen` | `/NewSpotScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Perfil` | `/Perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/CustomInput`; params?: Router.UnknownInputParams; } | { pathname: `/components/SpottedUALogo`; params?: Router.UnknownInputParams; } | { pathname: `/components/SppotedCard`; params?: Router.UnknownInputParams; } | { pathname: `/mocks/SpottedMocksData`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/Loguin` | `/Loguin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/Register` | `/Register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Chat` | `/Chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/NewSpotScreen` | `/NewSpotScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Perfil` | `/Perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/components/CustomInput`; params?: Router.UnknownOutputParams; } | { pathname: `/components/SpottedUALogo`; params?: Router.UnknownOutputParams; } | { pathname: `/components/SppotedCard`; params?: Router.UnknownOutputParams; } | { pathname: `/mocks/SpottedMocksData`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/Loguin${`?${string}` | `#${string}` | ''}` | `/Loguin${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/Register${`?${string}` | `#${string}` | ''}` | `/Register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Chat${`?${string}` | `#${string}` | ''}` | `/Chat${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/NewSpotScreen${`?${string}` | `#${string}` | ''}` | `/NewSpotScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Perfil${`?${string}` | `#${string}` | ''}` | `/Perfil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/components/CustomInput${`?${string}` | `#${string}` | ''}` | `/components/SpottedUALogo${`?${string}` | `#${string}` | ''}` | `/components/SppotedCard${`?${string}` | `#${string}` | ''}` | `/mocks/SpottedMocksData${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Loguin` | `/Loguin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Register` | `/Register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Chat` | `/Chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/NewSpotScreen` | `/NewSpotScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Perfil` | `/Perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/CustomInput`; params?: Router.UnknownInputParams; } | { pathname: `/components/SpottedUALogo`; params?: Router.UnknownInputParams; } | { pathname: `/components/SppotedCard`; params?: Router.UnknownInputParams; } | { pathname: `/mocks/SpottedMocksData`; params?: Router.UnknownInputParams; };
    }
  }
}
